# Generated by Django 4.0.4 on 2022-05-22 13:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default='0123456789', help_text='phone number of the student', max_length=10, verbose_name='phonenumber'),
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='', help_text='Reason about student missing', max_length=255, verbose_name='reason')),
                ('isMissing', models.BooleanField(default=True, help_text='Student missing ?', verbose_name='isMissing')),
                ('date', models.DateField(default=datetime.datetime(2022, 5, 22, 15, 33, 9, 283361), verbose_name='Date of Student Missing')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='lycee.student')),
            ],
        ),
    ]
