# Generated by Django 4.0.4 on 2022-05-22 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0002_alter_student_phone_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 22, 15, 34, 4, 684197), verbose_name='Date of Student Missing'),
        ),
    ]
