# Generated by Django 4.0.4 on 2022-05-22 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0004_alter_presence_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 22, 15, 49, 48, 527002), verbose_name='Date of Student Missing'),
        ),
    ]
