# Generated by Django 4.0.4 on 2022-05-22 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0005_alter_presence_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 22, 16, 28, 40, 613914), verbose_name='Date of Student Missing'),
        ),
    ]
